### ISSUE TITLE
How to renew certificate?

### ISSUE THREAD

**Issue by whatbh** [yellowhat/searx-heroku#3]
Hi, noob here. this is not exactly an issue. But I want to ask once the certificate expire, how can I renew it so I can continue to use https? 

Thank you very much.

**Comment by yellowhat** [comment]
The certificate is managed by heroku. Not what you are referring to.

**Comment by whatbh** [comment]
Oops, that's my problem. I don't know why recently Chrome keeps redirecting me to the http site, but I tried with another browser and https site is still working. Weird behavior but that's a me problem. Thanks.

**Comment by yellowhat** [comment]
No problem
